title: Skateboard Documentation
description: A modern React boilerplate with authentication, payments, and beautiful UI components
url: "https://stevederico.github.io"
baseurl: "/skateboard"

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-titles-from-headings
